length=float(input('Please enter the length of the rectangle: '))
width=float(input('Please enter the width of the rectangle: '))
perimeter=2*(length+width)
area=(length*width)
print("Perimeter of the rectangle is:", perimeter)
print("Area of the rectangle is:", area)
